<?php
require "connect.php";
$sql_task = "INSERT INTO `Task` (`ProjectID`, `UserID`, `TaskID`, `TaskName`, `TaskProgress`)
VALUES
('PJ01', 'ST01', 'TSK01', 'Homepage Design', 'Completed'),
('PJ01', 'ST02', 'TSK02', 'CSS Styling', 'Completed'),
('PJ01', 'ST12', 'TSK03', 'UI Enhancement', 'Completed'),
('PJ02', 'ST01', 'TSK04', 'Empathic Design', 'Completed'),
('PJ03', 'ST12', 'TSK05', 'General Graphics', 'Completed'),
('PJ04', 'ST02', 'TSK06', 'Animations', 'Completed'),
('PJ05', 'ST12', 'TSK07', 'Wireframing', 'Completed'),
('PJ05', 'ST02', 'TSK08', 'Prototyping', 'Completed'),
('PJ06', 'ST01', 'TSK09', 'Media Queries', 'In Progress'),
('PJ07', 'ST03', 'TSK10', 'Relative Units', 'In Progress'),
('PJ08', 'ST20', 'TSK11', 'Milestones Achieved', 'In Progress'),
('PJ09', 'ST20', 'TSK12', 'Next Meeting Details', 'In Progress'),
('PJ10', 'ST20', 'TSK13', 'Adjournment', 'In Progress'),
('PJ11', 'ST03', 'TSK14', 'New Business', 'In Progress'),
('PJ12', 'ST20', 'TSK15', 'Attendees', 'In Progress'),
('PJ12', 'ST03', 'TSK16', 'Feedback Mechanism', 'In Progress'),
('PJ13', 'ST03', 'TSK17', 'Regular Review', 'In Progress'),
('PJ14', 'ST04', 'TSK18', 'Coverage', 'In Progress'),
('PJ15', 'ST17', 'TSK19', 'Team Progress', 'In Progress'),
('PJ16', 'ST05', 'TSK20', 'Fluid Grids', 'In Progress'),
('PJ17', 'ST10', 'TSK21', 'Breakpoints', 'In Progress'),
('PJ18', 'ST04', 'TSK22', 'User Flow', 'In Progress'),
('PJ19', 'ST17', 'TSK23', 'Information Architecture', 'In Progress'),
('PJ20', 'ST05', 'TSK24', 'User Personas', 'Completed'),
('PJ21', 'ST10', 'TSK25', 'User Research', 'Completed'),
('PJ22', 'ST17', 'TSK26', 'Special Effects', 'Completed'),
('PJ23', 'ST04', 'TSK27', 'Environment Design', 'Completed'),
('PJ24', 'ST17', 'TSK28', 'Concept Art', 'Completed'),
('PJ24', 'ST10', 'TSK29', 'Legal Considerations', 'In Progress'),
('PJ24', 'ST05', 'TSK30', 'Adaptability', 'In Progress'),
('PJ25', 'ST17', 'TSK31', 'Flowcharts', 'In Progress'),
('PJ26', 'ST04', 'TSK32', 'Employee Handbook', 'In Progress'),
('PJ27', 'ST17', 'TSK33', 'Documentation Templates', 'In Progress'),
('PJ27', 'ST10', 'TSK34', 'Collaboration Tools', 'Completed'),
('PJ27', 'ST04', 'TSK35', 'Development Resources', 'In Progress'),
('PJ28', 'ST05', 'TSK36', 'Calibration Documents', 'Completed'),
('PJ28', 'ST10', 'TSK37', 'Performance Metrics', 'In Progress'),
('PJ29', 'ST05', 'TSK38', 'Self-Assessment Forms', 'In Progress'),
('PJ29', 'ST10', 'TSK39', 'Hiring Managers', 'Completed'),
('PJ29', 'ST17', 'TSK40', 'Recruitment Analytics', 'In Progress'),
('PJ30', 'ST04', 'TSK41', 'Offer Letter', 'In Progress'),
('PJ31', 'ST07', 'TSK42', 'Facilitator Guides', 'In Progress'),
('PJ32', 'ST06', 'TSK43', 'Assessment and Evaluation', 'Completed'),
('PJ33', 'ST09', 'TSK44', 'Presentation Slides', 'Completed'),
('PJ33', 'ST06', 'TSK45', 'Job Fair', 'Completed'),
('PJ34', 'ST07', 'TSK46', 'Network Contacts', 'Completed'),
('PJ34', 'ST09', 'TSK47', 'Email Correspondence', 'Completed'),
('PJ34', 'ST06', 'TSK48', 'Job Search Tracker', 'Completed'),
('PJ35', 'ST07', 'TSK49', 'Documentation', 'Completed'),
('PJ36', 'ST08', 'TSK50', 'Keyword Research Documents', 'In Progress'),
('PJ36', 'ST09', 'TSK51', 'Press Releases', 'Completed'),
('PJ37', 'ST16', 'TSK52', 'Online Advertisements', 'In Progress'),
('PJ38', 'ST10', 'TSK53', 'Brochures and Flyers', 'In Progress'),
('PJ38', 'ST11', 'TSK54', 'Technical Specifications', 'Completed'),
('PJ38', 'ST06', 'TSK55', 'Feature Definition', 'Completed'),
('PJ39', 'ST13', 'TSK56', 'API Documentation', 'In Progress'),
('PJ40', 'ST05', 'TSK57', 'Visual Representations', 'In Progress'),
('PJ40', 'ST12', 'TSK58', 'Executive Summary', 'In Progress'),
('PJ41', 'ST05', 'TSK59', 'Financial Highlights', 'In Progress'),
('PJ42', 'ST13', 'TSK60', 'Revenue Reports', 'In Progress'),
('PJ42', 'ST12', 'TSK61', 'Emergency Fund', 'Completed'),
('PJ42', 'ST05', 'TSK62', 'Editing Scripts', 'In Progress'),
('PJ43', 'ST12', 'TSK63', 'Equipment List', 'In Progress'),
('PJ44', 'ST13', 'TSK64', 'Raw Footage', 'Completed'),
('PJ44', 'ST05', 'TSK65', 'Color Grading', 'In Progress'),
('PJ45', 'ST12', 'TSK66', 'UGC Strategy', 'Completed'),
('PJ46', 'ST14', 'TSK67', 'UAT Schedule', 'In Progress'),
('PJ46', 'ST15', 'TSK68', 'Bug Resolution', 'Completed'),
('PJ46', 'ST04', 'TSK69', 'Reproduce Bugs', 'In Progress'),
('PJ47', 'ST04', 'TSK70', 'Bug Lifecycle Documentation', 'Completed'),
('PJ47', 'ST14', 'TSK71', 'Test Data Versioning', 'In Progress'),
('PJ48', 'ST15', 'TSK72', 'Baseline Test Results', 'In Progress'),
('PJ49', 'ST15', 'TSK73', 'Testing Frameworks', 'In Progress'),
('PJ50', 'ST16', 'TSK74', 'Test Execution Logs', 'In Progress'),
('PJ50', 'ST17', 'TSK75', 'User Acceptance', 'Completed'),
('PJ50', 'ST03', 'TSK76', 'Change Requests', 'Completed'),
('PJ51', 'ST17', 'TSK77', 'Deployment Scripts', 'In Progress'),
('PJ51', 'ST03', 'TSK78', 'Rollback Plan', 'In Progress'),
('PJ52', 'ST16', 'TSK79', 'Testing Protocols', 'Completed'),
('PJ52', 'ST03', 'TSK80', 'System Inventory', 'In Progress'),
('PJ53', 'ST03', 'TSK81', 'Recovery Point', 'In Progress'),
('PJ54', 'ST16', 'TSK82', 'Backup Software', 'In Progress'),
('PJ55', 'ST17', 'TSK83', 'Change Management', 'Completed'),
('PJ55', 'ST03', 'TSK84', 'Risk Management', 'Completed'),
('PJ55', 'ST17', 'TSK85', 'Interaction Alchemy', 'Completed'),
('PJ56', 'ST16', 'TSK86', 'Usability Uplift', 'Completed'),
('PJ56', 'ST03', 'TSK87', 'Journey Mapping', 'Completed'),
('PJ57', 'ST17', 'TSK88', 'Branding Alignment', 'In Progress'),
('PJ57', 'ST16', 'TSK89', 'Mobile Adaptation', 'In Progress'),
('PJ58', 'ST03', 'TSK90', 'Persona Development', 'In Progress'),
('PJ59', 'ST03', 'TSK91', 'Flow Optimization', 'Completed'),
('PJ60', 'ST18', 'TSK92', 'Responsive UX', 'In Progress'),
('PJ60', 'ST19', 'TSK93', 'Feedback Integration', 'Completed'),
('PJ60', 'ST02', 'TSK94', 'Accessible Design', 'In Progress'),
('PJ61', 'ST02', 'TSK95', 'Expense Tracking', 'Completed'),
('PJ61', 'ST19', 'TSK96', 'Procurement Analysis', 'Completed'),
('PJ62', 'ST01', 'TSK97', 'Expense Approval', 'In Progress'),
('PJ62', 'ST14', 'TSK98', 'Budget Analysis', 'Completed')";

if ($connect->query($sql_task) === TRUE) {
    echo "Thêm dữ liệu thành công";
} else {
    echo "Error: " . $sql_task . "<br>" . $connect->error;
}

$connect->close();
?>